name: Build TigerBeetle for Debian

on:
  workflow_dispatch:
    inputs:
      tigerbeetle_version:
        description: The version of TigerBeetle to build.
        type: string
        required: true
      build_version:
        description: The build version.
        type: string
        required: true
      architecture:
        description: Architecture to build (amd64, arm64, or 'all' for all architectures)
        type: choice
        default: 'all'
        options:
          - 'all'
          - 'amd64'
          - 'arm64'

permissions:
  contents: write

jobs:
  build-tigerbeetle:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tigerbeetle-debian
        uses: actions/checkout@v4

      - name: Build TigerBeetle
        run: ./build.sh ${{ inputs.tigerbeetle_version }} ${{ inputs.build_version }} ${{ inputs.architecture }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: tigerbeetle_*.deb


  release-tigerbeetle:
    name: (Draft-)Release TigerBeetle for Debian
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-tigerbeetle
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: tigerbeetle_*.deb
          name: ${{ inputs.tigerbeetle_version }}+${{ inputs.build_version }}
          tag_name: ${{ env.RELEASE_TAG }}
          fail_on_unmatched_files: true
